version: "3.2"

services:
    php80:
        image: php:8.0-cli-alpine
        volumes:
            - ./:/app
        user: ${HOST_UID}:${HOST_GID}
        working_dir: /app
        depends_on:
            - fake_leanpub_server
        env_file:
            - .env.test

    php74:
        image: php:7.4-cli-alpine
        volumes:
            - ./:/app
        user: ${HOST_UID}:${HOST_GID}
        working_dir: /app
        depends_on:
            - fake_leanpub_server
        env_file:
            - .env.test

    composer:
        image: composer:latest
        volumes:
            - ./:/app
        user: ${HOST_UID}:${HOST_GID}

    fake_leanpub_server:
        image: php:7.4-cli-alpine
        ports:
            - "8080:8080"
        volumes:
            - .:/app:cached
        working_dir: /app
        stop_signal: SIGINT
        entrypoint: "php -S 0.0.0.0:8080 integration-tests/FakeServer/router.php"
